config/routes.rb
Fittedly::Application.routes.draw do
  devise_for :users
 root 'pages#home'
 get "faq" => "pages#faq"
 get "about" => "pages#about"
 get "blog" => "pages#blog"
 get "start" => "pages#start"
 get "stylesform" => "pages#stylesform"
 get "lifestyle" => "pages#lifestyle"
 get "profile" => "pages#profile"
 get "account" => "pages#account"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  	#interaction with database here
  def about
  end
  def faq
  end
  def blog
  end
  def start
  end
  def stylesform
  end
  def lifestyle
  end
  def profile
  end
  def account
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<h4> footer </h4>
 	<li><%= link_to "Home", root_path %></li>
 	<li><%= link_to "About", about_path %></li>
  <li><%= link_to "FAQ", faq_path %></li> 

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
        <%= link_to "Fittedly", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
         
          <% if user_signed_in? %>
            <li><%= "Welcome user name, you have x credits to spend on clothes" %>
            <li><%= link_to "profile", profile_path %></li>
            <li><%= link_to "account", account_path %></li>  
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li> 
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li> 
           <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
  </div>

app/views/layouts/_start.html.erb
	<div class="well well-lg"><div class="container"><h2> Welcome to fittedly </h2>
	<p> hi %formname% We're excited to start styling you.  Our Style profile helps us get a sense of where your style is now and where you would like it to be.  We're ready to start asking questions, if you're ready to start answering them.  Don't forget - the more we know about you, the better we can sytle for you! (we currently carry sizes 0-14 or XS-XL and we're actively working to increase our range so that we can serve more women well.) </p></div>
</div>
</div>

<div class ="container" id="stylestart">
	<h2> Fit </h2>
<div class="progress">
	  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 25%">
	    <span class="sr-only">25% Complete (success)</span>
  </div>
</div>
	<h3>Date of Birth </h4>
	<%= date_field(:user, :born_on) %>
	<hr>
	<h4> Height?</h4>
	<%= number_field(:height, :feet, in: 4..6) %>  feet <%= number_field(:height, :inches, in: 0..11) %> inches
	<hr>
	<h4> Weight?-needs fix </h4>
	<%= number_field(:weight, :lbs, in: 90..250) %> lbs

	<hr>
	<h4> Bra size? - needs fix </h4>
	<%= number_field(:brasize, :inches, in: 30..42) %> 
	<%= number_field(:brasize, :inches, in: 30..42) %> 
	<hr>
	<h4> Dress size? </h4>
	<%= number_field(:brasize, :inches, in: 30..42) %> <%= link_to "Size Chart", faq_path %>
	<hr>
	<h4>What size do you normally wear for blouses and shirts? </h4>
	<%= text_field_tag(:query) %>
	<hr>
	<h4> What size do you normally wear for skirts and pants?</h4>
	<%= text_field_tag(:query) %>
	<hr>
	<h4>How do you prefer clothes to fit the top half of your body?</h4>
		<%= text_field_tag(:query) %>
	<hr>
	<h4>How do you prefer clothes to fit the top half of your body?</h4>
		<%= text_field_tag(:query) %>
	<hr>
	<h4> Are you curvy on your bottom half?</h4>
	<%= radio_button_tag(:yes, "yes") %> Yes
	<%= radio_button_tag(:no, "no") %>  No
	<hr>
	<h4> How would you characterize your proportions? </h4>
	Torso <%= text_field_tag(:query) %> Arms <%= text_field_tag(:query) %> Legs <%= text_field_tag(:query) %> Shoulders <%= text_field_tag(:query) %> Hips <%= text_field_tag(:query) %>

<hr>

		<%= link_to "Next", stylesform_path, class: "btn btn-success btn-lg"%>
	<hr>
</div> <!-- container style start end-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Fittedly</title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">


</head>
<body>
<%=render 'layouts/header'%>
<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

<%= yield %>
<%=render 'layouts/footer'%>


</body>
</html>

app/views/pages/about.html.erb
<h1> about </h1>

app/views/pages/account.html.erb
<h1> user account </h1>

app/views/pages/blog.html.erb
<h1> Blog </h1>

app/views/pages/faq.html.erb
<h1>faq</h1>

app/views/pages/home.html.erb
<% if user_signed_in? %>
		<%=render 'layouts/start'%>
<% else %>
				<div class="jumbotron" style="background-image: url('https://d27bvhtwhzf6pr.cloudfront.net/assets/new_banner-d1fdff3642bdd73012a9991640ec89ae.jpg'); min-height: 408px;">

			<div class="container" style="margin-left: 120px; margin-top: 50px; color: white;">
				<h1>Unleash Your Style</h1>
				<p>We'll guide the way </p>

					<%= link_to "Get Fitted", start_path, class: "btn btn-default btn-lg"%>
					<%= link_to "Devise New User Reg", new_user_registration_path, class: "btn btn-default btn-lg"%>
					<%= link_to "Devise existing user login", new_user_session_path, class: "btn btn-default btn-lg"%>

<%= form_for(:user, :url => session_path(:user)) do |f| %>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %>
  <%= f.submit 'Sign in' %>
  <%= link_to "Forgot your password?", new_password_path(:user) %>
<% end %>

			</div>
		</div>

		<div class="jumbotron">
			<h2 style="text-align: center;"> Awesome Message Here </h2>
		</div>
		<!-- why -->
			<div id="features">
				<div class="container">
					<div class="row feature">
						<div class="col-md-6 info">
							<h2>You appreciate great style</h2>
						</div>
						<div class="col-md-6 image">
							<!-- <img src="#" class="img-responsive" alt="feature1" /> -->
						</div>
					</div>
					
					<div class="row feature">
									<div class="col-md-6 image">
											<!-- <img src="images/feature1.png" class="img-responsive" alt="feature1" /> -->
						</div>
							<div class="col-md-6 info">
							<h2>...But you don't have time to shop for it</h2>
						</div>
					</div>

						<div class="row feature">
						<div class="col-md-6 info">
							<h2>That's where Fittedly comes in</h2>
						</div>
						<div class="col-md-6 image">
							<!-- <img src="images/feature1.png" class="img-responsive" alt="feature1" /> -->
						</div>
					</div>
					</div>

		<!-- how it works -->
		<div class="jumbotron" id="howitworks">
			<h2 style="text-color: gray; text-align: center;"> How does Fittedly Work? </h2>
		<!-- ****need media queries for this grid system -->
			<div class="container">
			<div class="row">
			  <div class="col-md-4"><h4>Create your Style Profile</h4></div>
			  <div class="col-md-4"><h4>Get 5 Handpicked Items</h4></div>
			  <div class="col-md-4"><h4>Keep what you like and send back the rest</h4></div>
			</div>
		</div>
		</div> <!-- container div end -->

		<div class="container" id="homeabout">
			<h2> Online Women's Personal Styling</h2>
			<div class="row">
		  	<div class="col-xs-6"><img alt="house" height="48" src="https://d27bvhtwhzf6pr.cloudfront.net/assets/svg/home-74daa69079a73a8346e5315fa50b0820.svg" width="48"> Try it on in the privacy of your own home <p class="home-features"> Try it on in the privacy of your won home, withyour own wardrobe.</p></div>
		    <div class="col-xs-6"><img alt="mailbox" height="48" src="https://d27bvhtwhzf6pr.cloudfront.net/assets/svg/mailbox-a4fc8d714928cb3fb3a993c4ca3b2780.svg" width="48">Free & Easy Returns</div>
		     <div class="col-xs-6"><img alt="shirt" height="48" src="https://d27bvhtwhzf6pr.cloudfront.net/assets/svg/shirt-5106e41390c3abcdd16da13f06e51afa.svg" width="48">Styling Tips</div>
		     
		      <div class="col-xs-6"><img alt="chart" height="48" src="https://d27bvhtwhzf6pr.cloudfront.net/assets/svg/chart-4e25df9b2ae02c56139d27f197ca8a07.svg" width="48">Better Over Time</div>
		</div>
		</div>


		<div class="jumbotron" id="start">
			<h2> signup form </h2>
			<%= link_to "Get Started", start_path, class: "btn btn-success btn-lg"%>

		</div>
<% end %>

app/views/pages/lifestyle.html.erb
<h1>lifestyle</h1>

app/views/pages/profile.html.erb
<h1> user style profile </h1>

app/views/pages/start.html.erb
	<div class="well well-lg"><div class="container"><h2> Welcome to fittedly </h2>
	<p> hi %formname% We're excited to start styling you.  Our Style profile helps us get a sense of where your style is now and where you would like it to be.  We're ready to start asking questions, if you're ready to start answering them.  Don't forget - the more we know about you, the better we can sytle for you! (we currently carry sizes 0-14 or XS-XL and we're actively working to increase our range so that we can serve more women well.) </p></div>
</div>
</div>

<div class ="container" id="stylestart">
	<h2> Fit </h2>
<div class="progress">
	  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 25%">
	    <span class="sr-only">25% Complete (success)</span>
  </div>
</div>
	<h3>Date of Birth </h4>
	<%= date_field(:user, :born_on) %>
	<hr>
	<h4> Height?</h4>
	<%= number_field(:height, :feet, in: 4..6) %>  feet <%= number_field(:height, :inches, in: 0..11) %> inches
	<hr>
	<h4> Weight?-needs fix </h4>
	<%= number_field(:weight, :lbs, in: 90..250) %> lbs

	<hr>
	<h4> Bra size? - needs fix </h4>
	<%= number_field(:brasize, :inches, in: 30..42) %> 
	<%= number_field(:brasize, :inches, in: 30..42) %> 
	<hr>
	<h4> Dress size? </h4>
	<%= number_field(:brasize, :inches, in: 30..42) %> <%= link_to "Size Chart", faq_path %>
	<hr>
	<h4>What size do you normally wear for blouses and shirts? </h4>
	<%= text_field_tag(:query) %>
	<hr>
	<h4> What size do you normally wear for skirts and pants?</h4>
	<%= text_field_tag(:query) %>
	<hr>
	<h4>How do you prefer clothes to fit the top half of your body?</h4>
		<%= text_field_tag(:query) %>
	<hr>
	<h4>How do you prefer clothes to fit the top half of your body?</h4>
		<%= text_field_tag(:query) %>
	<hr>
	<h4> Are you curvy on your bottom half?</h4>
	<%= radio_button_tag(:yes, "yes") %> Yes
	<%= radio_button_tag(:no, "no") %>  No
	<hr>
	<h4> How would you characterize your proportions? </h4>
	Torso <%= text_field_tag(:query) %> Arms <%= text_field_tag(:query) %> Legs <%= text_field_tag(:query) %> Shoulders <%= text_field_tag(:query) %> Hips <%= text_field_tag(:query) %>

<hr>

		<%= link_to "Next", stylesform_path, class: "btn btn-success btn-lg"%>
	<hr>
</div> <!-- container style start end-->

app/views/pages/stylesform.html.erb
<div class="alert alert-success"> ?Name | ?Credits     <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Style Profile?", about_path %></li>
      <li><%= link_to "My Account?", faq_path %></li>  
      <li><%= link_to "My Credit?", faq_path %></li> 
       <li><%= link_to "Sign Out", faq_path %></li> 
    </ul>
</div>
<div class ="container" id="stylestart">
	<h2> Fit  (spaced) Style </h2>
	<div class="progress">
	  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
	    <span class="sr-only">50% Complete (success)</span>
  	</div>

</div>
 	<h4> How would you characterize your personal style? </h4>
	 	<p> Bohemian Chic	<%= text_field_tag(:query) %> </p>
	 	<p> Classy	<%= text_field_tag(:query) %> </p>
	 	<p> Glamorous	<%= text_field_tag(:query) %> </p>
	 	<p> Romantic	<%= text_field_tag(:query) %> </p>
	 	<p> Casual Chic	<%= text_field_tag(:query) %> </p>
	 	<p> Edgy	<%= text_field_tag(:query) %> </p>
	 	<p> Preppy	<%= text_field_tag(:query) %> </p>
	<hr>
	